# Question 5

In [1]:
f = open( '../prompts/5/shrek.txt', 'r')
transcript = f.read()
f.close()

## String Cleaning

In [2]:
# turn everything lowercase
transcript_lower = transcript.lower()

In [4]:
print ( transcript_lower[:1000] )

==transcript==
a ray of light shines down on a leather-bound storybook. the book opens and a voice begins reading its text:

shrek: once upon a time there was a [[storybook princess|lovely princess]]. but she had an enchantment upon her of a fearful sort which could only be broken by love's first kiss. she was locked away in a castle guarded by a terrible [[storybook dragon|fire-breathing dragon]]. many brave knights had attempted to free her from this dreadful prison, but none prevailed. she waited in the dragon's keep in the highest room of the tallest tower. for [[storybook prince|her true love]] and true love's first kiss.

the voice laughs. a big, green hand rips out a page of the book and shuts it closed.

shrek: like that's ever gonna happen. what a load of -

we see an outhouse and hear the sound of a toilet flushing. out steps [[shrek (character)|shrek]], an ogre, who tugs at his underwear and shakes his foot of

In [8]:
#get a list of words
words = transcript_lower.split( ' ' )
words = [ word.strip() for word in words ]

In [9]:
print ( words[:100] )

['==transcript==\na', 'ray', 'of', 'light', 'shines', 'down', 'on', 'a', 'leather-bound', 'storybook.', 'the', 'book', 'opens', 'and', 'a', 'voice', 'begins', 'reading', 'its', 'text:', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 'shrek:', 'once', 'upon', 'a', 'time', 'there', 'was', 'a', '[[storybook', 'princess|lovely', 'princess]].', 'but', 'she', 'had', 'an', 'enchantment', 'upon', 'her', 'of', 'a', 'fearful', 'sort', 'which', 'could', 'only', 'be', 'broken', 'by', "love's", 'first', 'kiss.', 'she', 'was', 'locked', 'away', 'in', 'a', 'castle', 'guarded', 'by', 'a', 'terrible', '[[storybook', 'dragon|fire-breathing', 'dragon]].', 'many', 'brave', 'knights', 'had', 'attempted', 'to', 'free', 'her', 'from', 'this', 'dreadful', 'prison,', 'but', 'none', 'prevailed.', 'she', 'waited', 'in', 'the', "dragon's"]

In [10]:
love_words = [ word for word in words if 'love' in word ]

In [12]:
print ( love_words[:100] )

['princess|lovely', "love's", 'love]]', "love's", 'love', 'lovely!', 'lovely', 'love', 'lovely', 'loves', 'love', 'love', 'love', "love's", 'love?', 'love!', 'love!', 'love.', 'love', 'love', "love's", "love's", 'love', "love's", 'love', 'love.', 'love', 'love', 'love', 'love', 'love', 'love', 'love', 'love.', 'love?!', 'love', 'love,', 'love', 'love', "love's", "love's", "love's", "love's"]

In [13]:
import pandas as pd
df_love_words = pd.DataFrame( {'word': love_words} )

In [14]:
df_love_words

               word
0   princess|lovely
1            love's
2            love]]
3            love's
4              love
5           lovely!
6            lovely
7              love
8            lovely
9             loves
10             love
11             love
12             love
13           love's
14            love?
15            love!
16            love!
17            love.
18             love
19             love
20           love's
21           love's
22             love
23           love's
24             love
25            love.
26             love
27             love
28             love
29             love
30             love
31             love
32             love
33            love.
34           love?!
35             love
36            love,
37             love
38             love
39           love's
40           love's
41           love's
42           love's

In [15]:
df_love_words['word'].value_counts()

love               19
love's             10
love.               3
lovely              2
love!               2
princess|lovely     1
love]]              1
lovely!             1
loves               1
love?               1
love?!              1
love,               1
Name: word, dtype: int64

In [16]:
def remove_punctuation( word: str ) -> str:

    """given a word, remove the punctuation"""

    punctuation = ['!','?',',','.',']]'] #do not include apostrophe
    for punc in punctuation:
        word = word.replace( punc, '' )

    return word

In [17]:
remove_punctuation('love????')

'love'

In [18]:
df_love_words['stripped'] = df_love_words['word'].apply( lambda word: remove_punctuation(word) )

In [19]:
df_love_words

               word         stripped
0   princess|lovely  princess|lovely
1            love's           love's
2            love]]             love
3            love's           love's
4              love             love
5           lovely!           lovely
6            lovely           lovely
7              love             love
8            lovely           lovely
9             loves            loves
10             love             love
11             love             love
12             love             love
13           love's           love's
14            love?             love
15            love!             love
16            love!             love
17            love.             love
18             love             love
19             love             love
20           love's           love's
21           love's           love's
22             love             love
23           love's           love's
24             love             love
25            love.             love
26             love             love
27             love             love
28             love             love
29             love             love
30             love             love
31             love             love
32             love             love
33            love.             love
34           love?!             love
35             love             love
36            love,             love
37             love             love
38             love             love
39           love's           love's
40           love's           love's
41           love's           love's
42           love's           love's

In [20]:
df_love_words['stripped'].value_counts()

love               28
love's             10
lovely              3
princess|lovely     1
loves               1
Name: stripped, dtype: int64

In [21]:
df_love_words['is_love'] = df_love_words['stripped'].isin( ['love',"love's"] )

In [22]:
df_love_words.head()

              word         stripped  is_love
0  princess|lovely  princess|lovely    False
1           love's           love's     True
2           love]]             love     True
3           love's           love's     True
4             love             love     True

In [23]:
sum( df_love_words['is_love'] )

38